### ISSUE TITLE
Probleme d'encodage

### ISSUE THREAD

**Issue by wixaw** [piotrcki/wordlist#1]
Salut,
Quand je concatène les deux fichiers et que j'extrais le fichier .txt avec xz ou 7z, il sort avec l'encodage binary. Cela signifie que le fichier n'est pas un fichier texte et qu'il ne peut pas être utilisé directement avec des outils comme GregorBiswanger/WordlistRaider. De plus, je ne peux pas le convertir en UTF-8 avec iconv car le format est inconnu pour lui.

```
xz -v -d piotrcki-wordlist.txt.xz
piotrcki-wordlist.txt.xz (1/1)
  100 %       3179.5 MiB / 16.8 GiB = 0.185    38 MiB/s       7:34

file -i piotrcki-wordlist.txt
piotrcki-wordlist.txt: application/octet-stream; charset=binary


iconv -c -f binary -t utf-8 piotrcki-wordlist.txt > conv.txt
iconv: failed to start conversion processing: No such file or directory
```
Je te confirme que le sha512sum que j'obtiens est le même que toi

Si tu avais une solution
Merci

**Comment by piotrcki** [comment]
Bonjour,

Je pense que cela est du au fait que certains des mots de passe de la liste ont des encodages exotiques. Je ne les ai pas retiré ni ré-encodé car, comme ils sont issus de fuites, il se peut qu'il aient une utilité tels quels quelque part.

Est-ce gênant ?

Si oui, je pense qu'une des options est d'extraire uniquement les éléments encodés avec l'encodage souhaité à l'aide de la commande `strings` par exemple.

**Comment by wixaw** [comment]
Alors j'ai fait autrement , j'ai réécris le code avec un grep -i qui sait lire dans le binaire =)
Merci pour la liste 
++
